conditioning:
  method: fgps
  params:
    scale: 0.4 # only used if scale_schedule is 'fixed'.
    # Step size schedule.
    start_bound: 10
    end_bound: 75
    schedule: linear
    # Frequency schedule.
    scale_start: 2.0
    scale_end: 0.01
    scale_schedule: linear ##fixed

data:
  name: imagenet
  root: ./data/imagenet_samples/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.05
