conditioning:
  method: fgps
  params:
    scale: 0.4 # only used if scale_schedule is 'fixed'.
    # Frequency schedule.
    start_bound: 10
    end_bound: 75
    schedule: linear
    # Step size schedule.
    scale_start: 3.5
    scale_end: 0.6
    scale_schedule: linear ##fixed

data:
  name: imagenet
  root: ./data/imagenet_samples/

measurement:
  operator:
    name: high_pass
    kernel_size: 61
    intensity: 5

  noise: 
    name: gaussian
    sigma: 0.05
